services:
  - type: web
    name: whatsapp-bot-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: SCRAPER_API_URL
        value: https://chama-movie-api.koyeb.app
      - key: API_KEY
        value: chama_api_c82b12fffda71170b553f662d39426ec
      - key: FIREBASE_DATABASE_URL
        value: https://wa-sendr-bot-default-rtdb.firebaseio.com
